### PR TITLE
Bump to Sass 3.4 and Compass 1.0 (gemspec + Gemfile), updated tests control output

### PR DESCRIPTION
**Pull request by lolmaus**
This is a swifter duplicate of #72.

Test output:

```
$ bundle list | grep 'sass\|compass'
  * compass (1.0.1)
  * compass-core (1.0.1)
  * compass-import-once (1.0.5)
  * sass (3.4.0)


$ bundle exec ruby .unit_tests.rb
...
14 tests, 14 assertions, 0 failures, 0 errors, 0 skips
ruby -v: ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
```

### CODE REVIEW

**Comment by Snugug** [comment]
Resolves #72

**Comment by fubhy** [comment]
It would be great if you could leave a short notice (that you are going to take over) in the future before opening a new PR - As in giving me a chance to fix the PR. That way we don't run into this situation where two people work on the same stuff (wasting work time).

**Comment by lolmaus** [comment]
@fubhy I'm sorry your effort was wasted.

I did reference your PR from mine, though it doesn't spawn a notification. I could've been more explicit. @Snugug probably should've briefly explained the reason when closing your PR.

But when you saw your PR was closed, why didn't you look into why?

**Comment by fubhy** [comment]
Because I already started working on the next PR when @Snugug commented on it the first time ;)

**Comment by Snugug** [comment]
@fubhy this is my bad and I'm sorry. Given the time of day I thought you would be unavailable.

**Comment by fubhy** [comment]
No worries. Many things came together here (including me not actually checking back with GH before continuing to work on it and no e-mail notifications for referenced PRs, etc.). After all it was just a simple PR with literally only like 10 lines of search&replace fixes for the tests. So really not tragic.

**Pull request merged**
