### PR TITLE
Mixin for applying a value to multiple properties

### PR DESCRIPTION
**Pull request by Robovirtuoso**
This is a mixin I've found convenient when I have the same value I need applied to multiple properties such as `width`, `height`, `margin-left`, `margin-right`, etc.

### CODE REVIEW

**Comment by Snugug** [comment]
Please ensure there is a newline at the end of each file. Looks like we were missing our EditorConfig file; in there now.

**Comment by Robovirtuoso** [comment]
Will add a new line to the end of each file!

That makes sense, not having to worry about whether you have a comma or white-space separated list is a better API. 

`property` is a bit non-descriptive. What about just `assign` or `prop-set` ?

**Comment by Robovirtuoso** [comment]
Is there a way/does the error being thrown need to be tested? I can't find a Sass equivalent of Ruby's `rescue` or any way to test that an error is being thrown. It works when I test it manually.

Tests have been added to support the different list syntaxes. Will change the name as well. I'm cool with `assign`, `multiple-assign` or `property-set`.

**Comment by Snugug** [comment]
Manual testing for errors works for me. I'd go with multiple-assign or set-multiple

**Comment by Robovirtuoso** [comment]
Manual testing done and mixin renamed to `set-multiple`.

**Comment by Robovirtuoso** [comment]
How's it looking now? I removed the error function and made the commits more granular.

**Comment by Snugug** [comment]
All looks good, just waiting to hear back from Travis

**Comment by Snugug** [comment]
And there's Travis!

**Pull request merged**
